### ISSUE TITLE
Allow for nalaf to use SVMLight without precompiled binaries

### ISSUE THREAD

**Issue by ashishbaghudana** [Rostlab/relna#15]
- [ ] If using only SVMLight (not TK), this may create some incompatibility with trained models
- [ ] if using only SVMLight, faster approach is to use Python extension for SVMLight (https://pypi.python.org/pypi/svmlight)
- [ ] Upload Python 3 SVMLight extension

**Comment by juanmirocks** [comment]
but this is not for now, right? So far we just put TK. 

I am moving this to Maybe, unless you have an argument against it.

**Comment by juanmirocks** [comment]
The `svmlight.py` file (`class SVMLightTreeKernels`) was moved as is to to nalaf.

nalaf is now responsible for this and future development will decide whether use directly the python dependency (indeed better), or move altogether to another machine learning model for relationship extraction (e.g. convolutional networks)
