### ISSUE TITLE
Upload thesis & presentation slides to Wiki

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/relna#17]
- [x] Presentation
- [x] Thesis

**Comment by ashishbaghudana** [comment]
[Relation Extraction of TF and GGP](https://github.com/Rostlab/relna/files/49746/Relation.Extraction.of.TF.and.GGP.pdf)

**Comment by juanmirocks** [comment]
[Ashish Baghudana_bits_thesis.pdf](https://github.com/Rostlab/relna/files/311536/Ashish.Baghudana_bits_thesis.pdf)
