### ISSUE TITLE
Show slightly more detailed details of benchmarking on README

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/relna#9]
- [x] One graph with specific numbers (P, R, F1) and error bars
- [x] Tell right away in the introduction that this is the FIRST tool of its kind (to the best of our knowledge)

**Comment by ashishbaghudana** [comment]
![performance](https://cloud.githubusercontent.com/assets/3714983/11531733/438b2460-98ff-11e5-8332-e01d575570cc.png)
